version: '2'

services:
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_ZOOKEEPER_CONNECT: kafka-localhost:2181
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,SECURE:SASL_SSL
      KAFKA_CFG_LISTENERS: SECURE://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: SECURE://kafka-localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_CFG_MESSAGE_MAX_BYTES: 10226280
      KAFKA_CFG_LOG_RETENTION_BYTES: 10000000000
      KAFKA_CERTIFICATE_PASSWORD: changeit
      KAFKA_ZOOKEEPER_USER: kafka
      KAFKA_ZOOKEEPER_PASSWORD: pw123
      KAFKA_ZOOKEEPER_PROTOCOL: SASL
      KAFKA_BROKER_USER: kafka
      KAFKA_BROKER_PASSWORD: pw123
      KAFKA_CFG_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
      KAFKA_CFG_SUPER_USERS: "User:kafka"
      KAFKA_CFG_SASL_ENABLED_MECHANISMS: SCRAM-SHA-512
      KAFKA_INTER_BROKER_USER: kafka
      KAFKA_INTER_BROKER_PASSWORD: pw123
    volumes:
      #      - ./kafka/data:/bitnami/kafka
      - ./kafka/config/kafka.keystore.jks:/bitnami/kafka/config/certs/kafka.keystore.jks
      - ./kafka/config/kafka.truststore.jks:/bitnami/kafka/config/certs/kafka.truststore.jks
      - ./kafka/config/cacerts:/opt/bitnami/java/lib/security/cacerts
#      - ./kafka-acls.sh:/docker-entrypoint-initdb.d/kafka-acls.sh
    extra_hosts:
      - "kafka-localhost:192.168.1.21"
  zookeeper:
    image: bitnami/zookeeper
    ports:
      - '2181:2181'
    #    volumes:
    #      - ./zookeeper/data:/bitnami/zookeeper
    environment:
      ZOO_ENABLE_AUTH: 'yes'
      ZOO_SERVER_USERS: user1,kafka
      ZOO_SERVER_PASSWORDS: pass4user1,pw123
      ZOO_CLIENT_USER: user1
      ZOO_CLIENT_PASSWORD: pass4user1
